###
### Kibana with X-Pack Platinum configuration
###

version: "3.3"

services:
  kibana:
    environment:
      - XPACK_EDITION=${XPACK_EDITION}

  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}-x-pack
    environment:
      - XPACK_EDITION=${XPACK_EDITION}
      # TODO: Test with xpack.security and xpack.security.http.ssl enabled
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
