###
### Kibana with X-Pack Basic configuration
###

version: "3.3"

services:
  kibana:
    environment:
      - XPACK_EDITION=${XPACK_EDITION}

  elasticsearch:
    image: $(ELASTICSEARCH_IMAGE)-x-pack
    environment:
      - XPACK_EDITION=${XPACK_EDITION}
