###
### Kibana default configuration
###

version: "3.3"

networks:
  default:

services:
  kibana:
    image: ${DOCKER_IMAGE}
    depends_on:
      - elasticsearch
      - simple_ca
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - ELASTICSEARCH_URL=http://elasticsearch.local:9200
      - SERVER_CRT_HOST=${SERVER_CRT_HOST}
      - SERVER_KEY_PWD_FILE=/usr/share/kibana/config/server.pwd
      - SIMPLE_CA_URL=https://simple-ca.local
    # ports:
    #   - 5601:5601/tcp
    networks:
      default:
        aliases:
          - kibana.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro

  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    networks:
      default:
        aliases:
          - elasticsearch.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  simple_ca:
    image: ${SIMPLE_CA_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=simple-ca.local
    networks:
      default:
        aliases:
          - simple-ca.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_data:/var/lib/simple-ca
      - simple_ca_secrets:/var/lib/simple-ca/secrets

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - kibana
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - WAIT_FOR_TCP=kibana.local:5601
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - kibana
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - WAIT_FOR_TCP=kibana.local:5601
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  simple_ca_data:
  simple_ca_secrets:
  test_project_dir:
