version: 2
jobs:
  build_kibana: &build_kibana
    docker:
      - image: sicz/dockerspec
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Build and test Kibana image
          command: |
            cd ${CI_DIR}
            make ci
      - run:
          name: Save Docker image to workspace
          command: |
            cd ${CI_DIR}
            mkdir -p /tmp/workspace
            make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
            ls -lh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*.image"

  build_plugin: &build_plugin
    docker:
      - image: sicz/dockerspec
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Kibana image
          command: |
            cd ${CI_DIR}
            make docker-load-image clean DOCKER_IMAGE_DEPOT=/tmp/workspace
      - run:
          name: Build Kibana Plugin image
          command: |
            cd ${CI_DIR}
            make ci
      - run:
          name: Save Kibana Plugin image to workspace
          command: |
            cd ${CI_DIR}
            mkdir -p /tmp/workspace
            make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
            ls -lh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*.image"

  kibana-4.6.6:
    <<: *build_kibana
    environment:
      - CI_DIR=4.6.6
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-5.6.2:
    <<: *build_kibana
    environment:
      - CI_DIR=5.6.2
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-5.6.2-basic:
    <<: *build_plugin
    environment:
      - CI_DIR=5.6.2/basic
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-5.6.2-gold:
    <<: *build_plugin
    environment:
      - CI_DIR=5.6.2/gold
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-5.6.2-platinum:
    <<: *build_plugin
    environment:
      - CI_DIR=5.6.2/platinum
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-6.0.0:
    <<: *build_kibana
    environment:
      - CI_DIR=6.0.0
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-6.0.0-basic:
    <<: *build_plugin
    environment:
      - CI_DIR=6.0.0/basic
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-6.0.0-gold:
    <<: *build_plugin
    environment:
      - CI_DIR=6.0.0/gold
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-6.0.0-platinum:
    <<: *build_plugin
    environment:
      - CI_DIR=6.0.0/platinum
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  deploy:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make docker-load-image DOCKER_IMAGE_DEPOT=/tmp/workspace
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi

workflows:
  version: 2

  build:
    jobs:
      - kibana-4.6.6
      - kibana-5.6.2
      - kibana-5.6.2-basic:
          requires:
            - kibana-5.6.2
      - kibana-5.6.2-gold:
          requires:
            - kibana-5.6.2
      - kibana-5.6.2-platinum:
          requires:
            - kibana-5.6.2
      - kibana-6.0.0
      - kibana-6.0.0-basic:
          requires:
            - kibana-6.0.0
      - kibana-6.0.0-gold:
          requires:
            - kibana-6.0.0
      - kibana-6.0.0-platinum:
          requires:
            - kibana-6.0.0
      - deploy:
          requires:
            - kibana-4.6.6
            - kibana-5.6.2
            - kibana-5.6.2-basic
            - kibana-5.6.2-gold
            - kibana-5.6.2-platinum
            - kibana-6.0.0
            - kibana-6.0.0-basic
            - kibana-6.0.0-gold
            - kibana-6.0.0-platinum
