version: 2
jobs:
  build: &build
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Remote Docker engine version and images
          command: |
            docker --version
            docker-compose --version
            docker image ls
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - run:
          name: sicz/kibana
          command: |
            mkdir -p /tmp/workspace
            make ci
            make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
      - persist_to_workspace:
          root: /tmp/docker-images
          paths:
            - *.image

  "sicz/kibana:4.6.6":
    working_directory: 4.6.6
    <<: *build

  "sicz/kibana:5.6.0":
    working_directory: 5.6.0
    <<: *build

  "sicz/kibana:6.0.0":
    working_directory: 6.0.0
    <<: *build

  deploy:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Remote Docker engine version and images
          command: |
            docker --version
            docker-compose --version
            docker image ls
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make docker-load-image DOCKER_IMAGE_DEPOT=/tmp/workspace
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi

workflows:
  version: 2

  build:
    jobs:
      - "sicz/kibana:4.6.6"
      - "sicz/kibana:5.6.0"
      - "sicz/kibana:6.0.0"
      - deploy:
          requires:
            - "sicz/kibana:4.6.6"
            - "sicz/kibana:5.6.0"
            - "sicz/kibana:6.0.0"
