version: 2
jobs:
  build_kibana: &build_kibana
    docker:
      - image: sicz/dockerspec
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Pull Docker images
          command: |
            cd ${CI_DIR}
            make docker-pull-baseimage
            make docker-pull-image || true
            make docker-pull-dependencies
            make docker-pull-testimage
      - run:
          name: Build and test Kibana image
          command: |
            cd ${CI_DIR}
            make ci
      - run:
          name: Save Docker image to workspace
          command: |
            cd ${CI_DIR}
            mkdir -p /tmp/workspace
            make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
            ls -lh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*.image"

  build_plugin: &build_plugin
    docker:
      - image: sicz/dockerspec
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Pull Docker images
          command: |
            cd ${CI_DIR}/${PLUGIN_DIR}
            make docker-pull-image || true
            make docker-pull-dependencies
            make docker-pull-testimage
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Kibana base image
          command: |
            cd ${CI_DIR}/${BASEIMAGE_DIR}
            make docker-load-image DOCKER_IMAGE_DEPOT=/tmp/workspace
      - run:
          name: Build Kibana plugin image
          command: |
            cd ${CI_DIR}/${PLUGIN_DIR}
            make ci
      - run:
          name: Save Kibana plugin image to workspace
          command: |
            cd ${CI_DIR}/${PLUGIN_DIR}
            mkdir -p /tmp/workspace
            rm -f /tmp/workspace/*.image
            make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
            ls -lh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*.image"

  kibana-4.6.6:
    <<: *build_kibana
    environment:
      - CI_DIR=4.6.6
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-6.2.2:
    <<: *build_kibana
    environment:
      - CI_DIR=6.2.2
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-6.2.2-x-pack-basic:
    <<: *build_plugin
    environment:
      - CI_DIR=6.2.2
      - PLUGIN_DIR=x-pack-basic
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-6.2.2-x-pack-gold:
    <<: *build_plugin
    environment:
      - CI_DIR=6.2.2
      - PLUGIN_DIR=x-pack-gold
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  kibana-6.2.2-x-pack-platinum:
    <<: *build_plugin
    environment:
      - CI_DIR=6.2.2
      - PLUGIN_DIR=x-pack-platinum
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc

  # kibana-6.2.2-searchguard:
  #   <<: *build_plugin
  #   environment:
  #     - CI_DIR=6.2.2
  #     - PLUGIN_DIR=searchguard
  #     - BASEIMAGE_DIR=x-pack-basic
  #     - MAKEFLAGS=--no-print-directory
  #     - RSPEC_FORMAT=doc

  deploy:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make docker-load-image DOCKER_IMAGE_DEPOT=/tmp/workspace
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi

workflows:
  version: 2

  build:
    jobs:
      - kibana-4.6.6
      - kibana-6.2.2
      - kibana-6.2.2-x-pack-basic:
          requires:
            - kibana-6.2.2
      - kibana-6.2.2-x-pack-gold:
          requires:
            - kibana-6.2.2
      - kibana-6.2.2-x-pack-platinum:
          requires:
            - kibana-6.2.2
      # - kibana-6.2.2-searchguard:
      #     requires:
      #       - kibana-6.2.2-x-pack-basic
      - deploy:
          requires:
            - kibana-4.6.6
            - kibana-6.2.2
            - kibana-6.2.2-x-pack-basic
            - kibana-6.2.2-x-pack-gold
            - kibana-6.2.2-x-pack-platinum
            # - kibana-6.2.2-searchguard
