version: 2
jobs:
  kibana-4.6.6:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - run:
          name: sicz/kibana:4.6.6
          working_directory: 4.6.6
          command: |
            make ci
      - run:
          name: Save Docker image to workspace
          working_directory: 4.6.6
          command: |
            mkdir -p /tmp/workspace
            make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
            ls -l /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*.image"

  kibana-5.6.0:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - run:
          name: sicz/kibana:5.6.0
          working_directory: 5.6.0
          command: |
            make ci
      - run:
          name: Save Docker image to workspace
          working_directory: 5.6.0
          command: |
            mkdir -p /tmp/workspace
            make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
            ls -l /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*.image"

  kibana-6.0.0:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - run:
          name: sicz/kibana:6.0.0
          working_directory: 6.0.0
          command: |
            make ci
      - run:
          name: Save Docker image to workspace
          working_directory: 6.0.0
          command: |
            mkdir -p /tmp/workspace
            make docker-save-image DOCKER_IMAGE_DEPOT=/tmp/workspace
            ls -l /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*.image"

  deploy:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Remote Docker engine version and images
          command: |
            docker --version
            docker-compose --version
            docker image ls
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make docker-load-image DOCKER_IMAGE_DEPOT=/tmp/workspace
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi

workflows:
  version: 2

  build:
    jobs:
      - kibana-4.6.6
      - kibana-5.6.0
      - kibana-6.0.0
      - deploy:
          requires:
            - kibana-4.6.6
            - kibana-5.6.0
            - kibana-6.0.0
