### MK_DOCKER_IMAGE ############################################################

PROJECT_DIR		?= $(abspath ..)
VERSION_DIR		?= $(abspath .)
include $(VERSION_DIR)/kibana.mk

################################################################################
