### DOCKER_IMAGE ###############################################################

KIBANA_VERSION		?= 4.6.6

DOCKER_IMAGE_TAGS	?= 4.6 4

### BUILD ######################################################################

ELASTICSEARCH_VERSION	?= 2.4.5
ES_DISCOVERY_TYPE	?=
VARIANT_DIR		?= $(CURDIR)

### MK_DOCKER_IMAGE ############################################################

PROJECT_DIR		?= $(abspath ..)
include $(PROJECT_DIR)/docker.version.mk

################################################################################
